include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Use pub dependencies sorting from Pubspec Assist VSCode extension instead
    sort_pub_dependencies: false
    public_member_api_docs: false
