name: avataaars_models
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.2
  freezed: ^0.14.5
  json_serializable: ^5.0.1
  very_good_analysis: ^2.3.0
